# Generated by Django 4.2.1 on 2023-08-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_alter_product_id_alter_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='updated_at',
            new_name='update_at',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
